src/objects/Permit__c.object
<CustomObject>
    <description>Permits (Transportation, Building, Event, etc.) issued by the City of West Sacramento</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Application_Date__c</fullName>
        <label>Permit Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Permit_Fee__c</fullName>
        <description>Cost of obtaining permit</description>
        <formula>IF( ISPICKVAL(Permit_Type__c,&quot;Annual Transportation Permit&quot;), 90, 16)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Permit Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <displayFormat>PMT-{000000}</displayFormat>
        <label>Permit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSPaymentAlertController.cls
public class PSPaymentAlertController
{
  public PSPaymentAlertController()
  {

  }

  @AuraEnabled
  public static Map<String, String> getTaxDue()
  {
    System.debug('getTaxDue invoked...');

    Map<String, String> ret = new Map<String, String>();
    ret.put('amount', '0');
    ret.put('dueDate', '');


    User u = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];

    List<Permit__c> pList = [SELECT Id, Permit_Fee__c, Permit_Application_Date__c
                                     FROM Permit__c
                                    WHERE Contact__c = :u.ContactId AND Status__c = 'Approved'
                                    ORDER BY Permit_Application_Date__c ASC];



    if (pList != null && pList.size() > 0)
    {
       Integer amount = 0;
       for (Permit__c p : pList)
       {
          amount += p.Permit_Fee__c.intValue();
       }
       ret.put('amount', '' + amount);
       //ret.put('dueDate', DateTime.newInstance(pList[0].Due_Date__c.year(), pList[0].Due_Date__c.month(), pList[0].Due_Date__c.day()).format('YYYY-MM-dd'));
    }

    return ret;
  }

}