src/objects/PSLicense__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expires__c</fullName>
        <label>Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Item</label>
        <referenceTo>PSLicenseItem__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>License_Item__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>PSPayment__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Process</fullName>
                    <default>true</default>
                    <label>In-Process</label>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>License_Item__r.License_Type__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>LIC-{00000}</displayFormat>
        <label>PSLicense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSLicenseItem__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UOM__c</fullName>
        <label>UOM</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PSLicenseItem</label>
    <nameField>
        <displayFormat>LI-{00000}</displayFormat>
        <label>PSLicenseItem ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSLicenseItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PSPayment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_type__c</fullName>
        <label>Sub-type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Message__c</fullName>
        <label>Transaction Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{00000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PSLicenseSelectorController.cls
public with sharing class PSLicenseSelectorController
{
  public PSLicenseSelectorController()
  {

  }

   @AuraEnabled
  public static List<PSLicenseItem__c> getLicenseItems()
  {
    List<PSLicenseItem__c> itemList = [SELECT Id, Name__c, Description__c, Fee__c, Term__c, UOM__c FROM PSLicenseItem__c  ORDER BY createddate ASC];
    return itemList;
  }

  @AuraEnabled
  public static String storeLicenses(String params)
  {
  	System.debug('storeLicenses invoked...');
    Map<String, String> paramMap = (Map<String, String>)JSON.deserialize(params,   Map<String, String>.class);
    PSResponse resp = new PSResponse();

    try
    {
       List<String> licenseIds = (List<String>)JSON.deserialize(paramMap.get('licenseIds'),  List<String>.class);

       User u = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];

       List<PSLicenseItem__c> licItemList = [SELECT Id, Name__c, Fee__c, Term__c, UOM__c FROM PSLicenseItem__c WHERE Id IN :licenseIds];

       Date currDate = Date.today();

       PSPayment__c pmt = new PSPayment__c();
       pmt.Status__c = 'Paid';
       pmt.Amount__c = Decimal.valueOf(paramMap.get('amount'));
       pmt.Type__c = paramMap.get('type');
       pmt.Sub_Type__c = paramMap.get('subtype');
       pmt.Transaction_Date__c = currDate;
       pmt.Transaction_ID__c = paramMap.get('transactionId');
       pmt.Transaction_Message__c = paramMap.get('transactionMsg');
       insert pmt;

       List<PSLicense__c> licList = new List<PSLicense__c>();
       for (PSLicenseItem__c tmpLic : licItemList)
       {
        
         PSLicense__c lic = new PSLicense__c();
         lic.Payment__c = pmt.Id;
         lic.Contact__c = u.ContactId;
         lic.License_Item__c = tmpLic.Id;
         lic.Status__c = 'Valid';

       
         System.debug('UOM=' + tmpLic.UOM__c);
         if (tmpLic.UOM__c == 'Year')
         {
           lic.Expires__c = currDate.addYears((Integer)tmpLic.Term__c);
           System.debug('nextYear=' + lic.Expires__c);
         }
         else if (tmpLic.UOM__c == 'Month')
         {
          lic.Expires__c = currDate.addMonths((Integer)tmpLic.Term__c);
           System.debug('nextMonth=' + lic.Expires__c);
         }
         else {
           lic.Expires__c = currDate.addDays((Integer)tmpLic.Term__c);
           System.debug('nextDay=' + lic.Expires__c);
         }

         licList.add(lic);
         
       }

       if (licList.size() > 0) insert licList;
      
    }
    catch (exception e)
    {
      resp.status = PSResponse.ERROR;
      resp.msg = e.getMessage();
    }
    
    return  JSON.serialize(resp);
  }
}